import { c as createAstro, d as createComponent, r as renderTemplate, e as renderComponent, m as maybeRenderHead } from '../astro_6265eb83.mjs';
import 'html-escaper';
import 'clsx';
import { $ as $$Layout } from './about_922d4fa0.mjs';

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(raw || cooked.slice()) }));
var _a;
const $$Astro = createAstro();
const $$Contact = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Contact;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Varcoe - Get In Touch" }, { "default": ($$result2) => renderTemplate(_a || (_a = __template(["", `<section class="contact-box"><div class="container"><div class="contact-left"><div class="main-intro text-left"><h1>Don't be shy,<br>talk to me.</h1></div><form id="contact-form" method="post" action="mailer.php" role="form" novalidate="true"><div class="messages"></div><div class="form controls"><div class="input-half form-group"><label for="form_name">Name</label><input type="text" id="form_name" name="name" value="" class="input" required="required" data-error="A name is required." placeholder="Name/Business"><div class="help-block with-errors"></div></div><div class="input-half form-group" style="float:right;"><label for="form_email">Email</label><input id="form_email" type="email" name="email" value="" class="input" required="required" data-error="Valid email is required." placeholder="Email"><div class="help-block with-errors"></div></div><div class="input-full form-group"><label for="form_budgetl">Budget</label><select class="select" id="form_budget" name="budget" value="" required="required" data-error="Please choose budget."><option name="budget" value="$2000-2500" selected="selected">$2000-$2500</option><option name="budget" value="$3000-5000">$3000-$5000</option><option name="budget" value="$5000+">$5000+</option></select><div class="help-block with-errors"></div></div><script type="text/javascript">
                        var select = document.getElementById('form-budget');
                        select.onchange = function() {
                            select.className = 'selectactive';
                        }
                    <\/script><div class="input-full form-group"><label for="form_message">Message</label><textarea id="form_message" name="message" required="required" data-error="Please, leave us a message." class="textarea" placeholder="If you're requesting a quote please try to include as much information as possible about the project."></textarea><div class="help-block with-errors"></div></div><div class="input-full"><div class="form-group" style="margin-bottom:10px;"><div class="g-recaptcha" data-sitekey="6Ld0YI0UAAAAAM8deeF8pZaxCpeLFT8m4x064Y2A" data-callback="verifyRecaptchaCallback" data-expired-callback="expiredRecaptchaCallback"><div style="width: 304px; height: 78px;"><div><iframe title="reCAPTCHA" width="304" height="78" role="presentation" name="a-mx57041ivkf2" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox" src="https://www.google.com/recaptcha/api2/anchor?ar=1&k=6Ld0YI0UAAAAAM8deeF8pZaxCpeLFT8m4x064Y2A&co=aHR0cHM6Ly92YXJjb2UubmV0OjQ0Mw..&hl=en&v=lLirU0na9roYU3wDDisGJEVT&size=normal&cb=y3zjaiaf9jcs"></iframe></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid rgb(193, 193, 193); margin: 10px 25px; padding: 0px; resize: none; display: none;"></textarea></div><iframe style="display: none;"></iframe></div><input style="display:none !important;" class="form-control d-none" data-recaptcha="true" required="" data-error="Please complete the Captcha"><div class="help-block with-errors recaptchaerror"></div></div></div><div class="input-full"><input type="submit" value="Send Now" class="button disabled"></div></div></form></div><div class="one-third"><ul><li><img src="img/email.png" alt="Email" width="48" height="48"><h4><span>Direct Email</span><a href="mailto:korey@varcoe.net">korey@varcoe.net</a></h4></li><li><img src="img/skype.png" alt="Skype" width="48" height="48"><h4><span>Skype</span><a href="skype:varcoedesign?chat">varcoedesign</a></h4></li><li><img src="img/discord.png" alt="Skype" width="48" height="48"><h4><span>Discord</span><a href="skype:varcoedesign?chat">varcoenet</a></h4></li></ul></div><div class="clearfix"></div><a href="/" class="logofooter"></a></div></section>`])), maybeRenderHead()) })}`;
}, "/Applications/MAMP/htdocs/varcoenew/varcoe.net/src/pages/contact.astro", void 0);

const $$file = "/Applications/MAMP/htdocs/varcoenew/varcoe.net/src/pages/contact.astro";
const $$url = "/contact";

export { $$Contact as default, $$file as file, $$url as url };
