import { c as createAstro, d as createComponent, r as renderTemplate, m as maybeRenderHead, h as addAttribute, e as renderComponent } from '../astro_6265eb83.mjs';
import 'html-escaper';
import 'clsx';
import { $ as $$Layout } from './about_922d4fa0.mjs';

const $$Astro$1 = createAstro();
const $$WorkPreview = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$WorkPreview;
  const { link, imglink, title, services, type } = Astro2.props;
  return renderTemplate`${maybeRenderHead()}<section class="work-preview"><a class="container"${addAttribute(link, "href")}><span class="new">NEW</span><div class="content-left"><div class="work-logo"><img${addAttribute(imglink, "src")} alt=""></div><h2>${title}</h2><div class="work-footer"><span>${services}</span>${type}</div></div></a></section>`;
}, "/Applications/MAMP/htdocs/varcoenew/varcoe.net/src/components/work-preview.astro", void 0);

const $$Astro = createAstro();
const $$Ggservers = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Ggservers;
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Varcoe - GG Servers" }, { "default": ($$result2) => renderTemplate`${maybeRenderHead()}<section class="casestudy" style="background:#212538;"><div class="container"><div class="hero-center"><img src="img/ggserver/logo.png" alt="GG Servers"><h1>The foundation for a GG Minecraft provider.</h1><img src="img/ggserver/threepreviews.png" alt="" class="hero-center-img"></div><div class="clearfix"></div></div></section><section class="casestudy-main"><div class="container"><div class="casestudy-main-left"><h1>GG Servers</h1><h2>Minecraft and Game Server Hosting</h2><p>I was excited to work with the guys over at GG Servers again. This time around they were looking for a more modern and simpler website but keeping a similar look to their existing website. I cleaned up the website, switched to more modern coding and image standards that support retina, modernized their order page, and overall just made a great website that holds true to their existing brand!</p><a href="javascript:void(0)" class="button disabled">Link Coming Soon</a><p style="font-size:16px;padding-top:20px;">
Check out their old website I did for them <a href="ggservers/">here</a></p></div><div class="casestudy-main-right"><ul><li>Platform</li><li>Desktop</li><li>Mobile</li></ul><ul><li>Services</li><li>Website Design</li><li>Responsive Coding</li><li>WHMCS Order Form</li></ul></div><div class="clearfix"></div></div></section><section class="casestudy-preview"><div class="container"><ul class="nav nav-tabs" id="myTab"><li class="active"><a data-target="#colors" data-toggle="tab">Colors</a></li><li><a data-target="#typo" data-toggle="tab">Typography</a></li><li><a data-target="#icons" data-toggle="tab">Icons</a></li></ul><h2>Colors, Typography, and Icons.</h2><div class="tab-content"><div class="tab-pane active" id="colors"><div class="colorbox" style="background:#2b49ff;"><h3>Primary<br>Color</h3><span>#2B49FF</span></div><div class="colorbox" style="background:#ea2a2a;"><h3>Secondary<br>Color</h3><span>#ea2a2a</span></div><div class="colorbox" style="background:#02b77b;"><h3>Tertiary<br>Color</h3><span>#02b77b</span></div><div class="colorbox" style="background:#FFFFFF;color:#ced2db;"><h3 style="color:#afb4c1;">Header<br>Text</h3><span>#FFFFFF</span></div><div class="colorbox" style="background:#ADB2C8;"><h3>Body<br>Text</h3><span>#ADB2C8</span></div></div><div class="tab-pane" id="typo"><div class="one-half"><h1><small>Proxima Nova</small>The quick fox jumps over the lazy dog.</h1></div><div class="one-half"><h1><small>Proxima Nova</small></h1><p style="font-size:30px;line-height:36px;padding-top:16px;font-weight:400;">The quick fox jumps over the lazy dog.</p><p style="font-size:24px;line-height:30px;font-weight:400;">The quick fox jumps over the lazy dog.</p><p style="font-size:20px;line-height:26px;font-weight:400;">The quick fox jumps over the lazy dog.</p></div></div><div class="tab-pane" id="icons">
I decided on <a href="https://fontawesome.com/v6/" target="_blank">Font Awesome v6</a> for this project.
</div></div></div><div class="clearfix"></div></section><section class="cs-preview"><div class="container"><div class="small-header centered">
The Design
</div><h2>The new look</h2><div class="clickanywhere">Click any preview below to view in full<br>screen and additional pages</div><div class="one-third"><a data-fancybox="gallery" href="img/ggserver/two-big.png" class="fancybox"><img src="img/ggserver/two.png"></a></div><div class="one-third"><a data-fancybox="gallery" href="img/ggserver/one-big.png" class="fancybox"><img src="img/ggserver/one.png"></a></div><div class="one-third"><a data-fancybox="gallery" href="img/ggserver/three-big.png" class="fancybox"><img src="img/ggserver/three.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/four-big.png" class="fancybox"><img src="img/ggserver/four-big.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/five-big.png" class="fancybox"><img src="img/ggserver/five-big.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/six-big.png" class="fancybox"><img src="img/ggserver/six-big.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/seven-big.png" class="fancybox"><img src="img/ggserver/seven-big.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/eight-big.png" class="fancybox"><img src="img/ggserver/eight-big.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/nine-big.png" class="fancybox"><img src="img/ggserver/nine-big.png"></a></div><div class="one-third" style="display:none;"><a data-fancybox="gallery" href="img/ggserver/ten-big.png" class="fancybox"><img src="img/ggserver/ten-big.png"></a></div><div class="clearfix"></div></div></section><div class="inner-pagination work"><div class="streamlinebox one-half left">${renderComponent($$result2, "WorkPreview", $$WorkPreview, { "title": "The perfect combination of gaming and functionality", "imglink": "img/streamline/logo.svg", "link": "streamline", "services": "WEB DESIGN / CODING", "type": "Game Server Provider" })}</div><div class="shockbox one-half right">${renderComponent($$result2, "WorkPreview", $$WorkPreview, { "title": "A website designed to shock and awe", "imglink": "img/shockhosting/logo.png", "link": "shockhosting", "services": "WEB DESIGN / CODING", "type": "Hosting Provider" })}</div></div><div class="clearfix"></div>` })}`;
}, "/Applications/MAMP/htdocs/varcoenew/varcoe.net/src/pages/ggservers.astro", void 0);

const $$file = "/Applications/MAMP/htdocs/varcoenew/varcoe.net/src/pages/ggservers.astro";
const $$url = "/ggservers";

const ggservers = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Ggservers,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

export { $$WorkPreview as $, ggservers as g };
